server:
  port: 8005
spring:
  application:
    name: microservice-consumer
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  microservice-provider:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule